# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGQjLdw0K7KQt9D75nn9eh6exaOAcjwk
"""



import streamlit as st
import numpy as np
import joblib

# Load the trained Lasso model
model = joblib.load('lasso_model.pkl')

st.set_page_config(page_title="House Price Prediction", layout="centered")
st.title("🏠 House Price Prediction App")
st.write("This app predicts the house price based on selected features using a trained Lasso Regression model.")

# Sidebar for inputs
st.sidebar.header("Enter House Features")

# Input features (based on what you trained your model on)
gr_liv_area = st.sidebar.slider('Above ground living area (sq ft)', 500, 5000, 1500)
overall_qual = st.sidebar.slider('Overall Quality (1 = low, 10 = high)', 1, 10, 5)
year_built = st.sidebar.slider('Year Built', 1900, 2024, 2000)
garage_cars = st.sidebar.slider('Garage Capacity (cars)', 0, 5, 2)
total_bsmt_sf = st.sidebar.slider('Total Basement Area (sq ft)', 0, 3000, 800)

# Prepare data for prediction
input_data = np.array([[gr_liv_area, overall_qual, year_built, garage_cars, total_bsmt_sf]])

# Predict
if st.sidebar.button("Predict Price"):
    prediction = model.predict(input_data)[0]
    st.success(f"💰 Estimated Sale Price: ${prediction:,.2f}")
